import Head from 'next/head'
import { useEffect, useState } from 'react'
import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react'
import { useRouter } from 'next/router'
import { GridCardList, LinkTab, ProfileDetails, TabPanel } from '../../src/components'
import { BsJournalAlbum } from 'react-icons/bs'
import { Box, Tabs } from '@mui/material'
import { GetServerSidePropsContext } from 'next'
import { createServerSupabaseClient } from '@supabase/auth-helpers-nextjs'
import Link from 'next/link'
import { useDispatch } from 'react-redux'
import { callApiStart, callApiSuccess } from '../../src/redux/slices/apiSlice'

type Profiles = Database['public']['Tables']['profiles']['Row']

type Props = {
	data: Profiles
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
	// Create authenticated Supabase Client
	const supabase = createServerSupabaseClient(context)
	const bcuns_id: string | string[] | undefined = context.params?.bcuns_id

	const { data, error, status } = await supabase
		.from('profiles')
		.select()
		.eq('bcuns_id', bcuns_id)
		.single()

	return { props: { data } }
}

export default function Home(props: Props) {
	const supabase = useSupabaseClient<Database>()
	const profile: Profiles = props.data
	const session = useSession()
	const router = useRouter()
	const dispatch = useDispatch()
	// const bcuns_id: string | string[] | undefined = router.query.account

	// tablist
	const [value, setValue] = useState(0)
	const handleChange = (event: React.SyntheticEvent, newValue: number) => {
		setValue(newValue)
	}

	// console.log('router.query', router.query.account)

	const [comics, setComics] = useState<Array<
		Database['public']['Tables']['comics']['Row']
	> | null>()

	useEffect(() => {
		const func = async () => {
			dispatch(callApiStart())
			let { data: comics, error } = await supabase
				.from('comics')
				.select(`*, chapters(*)`)
				.range(0, 11)

			console.log('data: ', comics)
			console.log('error: ', error)

			setComics(comics)
			dispatch(callApiSuccess(true))
		}
		func()
	}, [])

	return (
		<>
			<Head>
				<title>{profile?.full_name} | BCuns</title>
				<meta name="description" content={`Generated by create next app`} />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{profile ? (
				<main className="px-4 sm:px-8">
					<>
						<ProfileDetails profile={profile} />
						{/* option */}
						<Box sx={{ width: '100%' }}>
							<Box sx={{ borderBottom: 1, borderColor: 'divider' }}>
								<Tabs value={value} onChange={handleChange} aria-label="basic tabs example">
									<LinkTab label="Truyện tranh" icon={<BsJournalAlbum size={18} color="red" />} />
								</Tabs>
							</Box>
							<TabPanel value={value} index={0}>
								<GridCardList list={comics} />
							</TabPanel>
						</Box>
					</>
				</main>
			) : (
				<main className="grid min-h-full place-items-center bg-white py-24 px-6 sm:py-32 lg:px-8">
					<div className="text-center">
						<p className="text-8xl font-semibold text-indigo-600">404</p>
						<h1 className="mt-4 text-3xl font-bold tracking-tight text-gray-900 sm:text-5xl">
							Page not found
						</h1>
						<p className="mt-6 text-base leading-7 text-gray-600">
							Sorry, we couldn’t find <b className='text-red-500'>bcuns id</b> the page you’re looking for.
						</p>
						<div className="mt-10 flex items-center justify-center gap-x-6">
							<Link
								href="/"
								className="rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
							>
								Go back home
							</Link>
							<Link href="/contact" className="text-sm font-semibold text-gray-900">
								Contact support <span aria-hidden="true">&rarr;</span>
							</Link>
						</div>
					</div>
				</main>
			)}
		</>
	)
}
