import { useTheme } from 'next-themes'
import Head from 'next/head'
import * as React from 'react'

export interface IHomeProps {}

export default function Home(props: IHomeProps) {

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="px-4 sm:px-8">
				Home page
			</main>
		</>
	)	
}
